### ISSUE TITLE
help needed on error

### ISSUE THREAD

**Issue by level14taken** [pytorch/xla#1758]
## ❓ Questions and Help
hey i have followed colab pytorch notebook as reference,but i ended with the following error

https://colab.research.google.com/drive/14L1VzxBC6QB-UCxg1sicfnBDZ9GwmIiF

last  cell is where error is present
following the error i found that the problem is with using Parallel loader but everything looks fine
can anyone help on this issue??

**Comment by dlibenzi** [comment]
Hi!
There has been a bug that we just fixed related to this:
```
RuntimeError: Aborted: Session f0da3fedf34cc9e1 is not found.
```
If you can try again with the latest nightly it should be OK.
Just remember to chose `nightly` in the `VERSION` listbox of the Colab cell.

**Comment by level14taken** [comment]
I restarted the colab session and rerun the whole notebook twice,with nightly  version  but the error still doesent go away.

**Comment by dlibenzi** [comment]
Yep, I confirmed myself with our standard MNIST Colab that the error is still there on nightly.
@jysohn23 Do you know when/how Colab picks them up?
You kicked a manual nightly yesterday, right?

**Comment by jysohn23** [comment]
I just reproed the failure too and it looks like what's happening is that the version we request is lagging by one day because of https://github.com/pytorch/xla/blob/master/contrib/scripts/env-setup.py#L33 where we request yesterday's nightly since the time that we publish the image at may not be exactly at the same time. In the longer term the auto version changer will support requests like `http://TPU_IP_ADDR:8475/requestversion/nightly` whereas right now it only supports `https://TPU_IP_ADDR:8475/requestversion/TPU-devYYYYMMDD`.

For now just try requesting `20200314` specifically in your setup cell but in the longer term fix is coming and should be rolled out in a week or so.

**Comment by level14taken** [comment]
Thanks for the help
