### ISSUE TITLE
I want to Multi-Node Multi GPU training, how should I configure the environment

### ISSUE THREAD

**Issue by ZhongYFeng** [pytorch/xla#3391]
## ❓ Questions and Help
Running XLA MultiGPU MultiNode，I know that I need to set XRT_SHARD_WORLD_SIZE and XRT_WORKERS, but I don't know how to configure the variable value of XRT_WORKERS.
Are there some examples that exist for me to refer to?

**Comment by JackCaoG** [comment]
I have not tried it personally, seems like @[cicirori](https://github.com/cicirori) has done it before. Do you mind sharing the config?

**Comment by cicirori** [comment]
> I have not tried it personally, seems like @[cicirori](https://github.com/cicirori) has done it before. Do you mind sharing the config?

@JackCaoG with pleasure

When xmp.spawn starts a GPU task, it ends up using a process to manage a card. xmp.spawn configures some environment variables for each process for distributed launch. The following lists the allowed environment variables and their meanings.

| env name | meaning | example value | 
| --- | --- | --- | 
| XRT_HOST_WORLD_SIZE | number of nodes | INT
| XRT_HOST_ORDINAL | node index(No need to configure, otherwise it will lead to incorrect operation) | INT |
| XRT_SHARD_WORLD_SIZE |  number of process (equals to gpu numbers) | INT |
| XRT_SHARD_ORDINAL | global index | INT |
| XRT_SHARD_LOCAL_ORDINAL | local index | INT |
| XRT_MESH_SERVICE_ADDRESS | tf mesh service addr | "${IP}:{PORT}" |
| XRT_WORKERS | global workers info | '&#124;'.join("localservice:${GLOBAL_INDEX};grpc://${IP}:${PORT}) | 
| XRT_DEVICE_MAP | gloabl device map info  | '&#124;'.join("/job:localservice/replica:0/task:${GLOBAL_INDEX}/device:XLA_GPU:0") |
| XRT_LOCAL_WORKER | per  worker name | "localservice:${GLOBAL_INDEX} |
| XRT_MULTI_PROCESSING_DEVICE | per worker device | "GPU:${GLOBAL_INDEX} | 



also, CUDA_VISIBLE_DEVICES is needed for per worker. then you need set device ahead in your code:
```
device = xm.xla_device()
xm.set_replication(device, [device])
```

**Comment by cicirori** [comment]
> I have not tried it personally, seems like @[cicirori](https://github.com/cicirori) has done it before. Do you mind sharing the config?

@JackCaoG I also develop a multi-node torch xla launch utility just like `torchrun`, would the community be willing to accept this feature?

**Comment by cicirori** [comment]
@JackCaoG and strayed from this topic...  I need help of [issue#3352](https://github.com/pytorch/xla/issues/3352)...

**Comment by JackCaoG** [comment]
@cicirori We'd love to take that change. FYI we are wokring on runtime migration so the way to start gpu training will likely change in the future(targeting q3 2022). We will keep XRT as runtime option at least until end of year through.

**Comment by cicirori** [comment]
> @cicirori We'd love to take that change. FYI we are wokring on runtime migration so the way to start gpu training will likely change in the future(targeting q3 2022). We will keep XRT as runtime option at least until end of year through.


Okay, but our pytorch version is fixed at 1.10 and I will evaluate the workload of merging into master (`xlarun` called some `torchrun` APIs).
And where can I see the progress related to runtime migration? Or does the corresponding item exist only internally in google?

**Comment by ZhongYFeng** [comment]
> > I have not tried it personally, seems like @[cicirori](https://github.com/cicirori) has done it before. Do you mind sharing the config?
> 
> @JackCaoG with pleasure
> 
> When xmp.spawn starts a GPU task, it ends up using a process to manage a card. xmp.spawn configures some environment variables for each process for distributed launch. The following lists the allowed environment variables and their meanings.
> 
> env name	meaning	example value
> XRT_HOST_WORLD_SIZE	number of nodes	INT
> XRT_HOST_ORDINAL	node index(No need to configure, otherwise it will lead to incorrect running)	INT
> XRT_SHARD_WORLD_SIZE	number of process (equals to gpu numbers)	INT
> XRT_SHARD_ORDINAL	global index	INT
> XRT_SHARD_LOCAL_ORDINAL	local index	INT
> XRT_MESH_SERVICE_ADDRESS	tf mesh service addr	"${IP}:{PORT}"
> XRT_WORKERS	global workers info	'|'.join("localservice:${GLOBAL_INDEX};grpc://${IP}:${PORT})
> XRT_DEVICE_MAP	gloabl device map info	'|'.join("/job:localservice/replica:0/task:${GLOBAL_INDEX}/device:XLA_GPU:0")
> XRT_LOCAL_WORKER	per worker name	"localservice:${GLOBAL_INDEX}
> XRT_MULTI_PROCESSING_DEVICE	per worker device	"GPU:${GLOBAL_INDEX}
> also, CUDA_VISIBLE_DEVICES is needed for per worker. then you need set device ahead in your code:
> 
> ```
> device = xm.xla_device()
> xm.set_replication(device, [device])
> ```

Thanks a lot for the answer. But I still encountered some problems, it should be a bug
In torch_xla/distributed/xla_multiprocessing.py file ，
https://github.com/pytorch/xla/blob/9917e41f60354ce96b3181acf30dff422d3c8716/torch_xla/distributed/xla_multiprocessing.py#L54-L63
https://github.com/pytorch/xla/blob/1f71ef2a7b99c6d148a006891a79d53db82f7f3b/torch_xla/distributed/xla_multiprocessing.py#L147-L175
In here worker does not have the property host_port, this should be wcfg[worker].host_port
https://github.com/pytorch/xla/blob/1f71ef2a7b99c6d148a006891a79d53db82f7f3b/torch_xla/distributed/xla_multiprocessing.py#L157
Same problem with these two lines
https://github.com/pytorch/xla/blob/1f71ef2a7b99c6d148a006891a79d53db82f7f3b/torch_xla/distributed/xla_multiprocessing.py#L160
https://github.com/pytorch/xla/blob/1f71ef2a7b99c6d148a006891a79d53db82f7f3b/torch_xla/distributed/xla_multiprocessing.py#L163
In addition, if XRT_WORKERS="localservice:0;grpc://localhost:40934|localservice:1;grpc://localhost:40937", 
https://github.com/pytorch/xla/blob/1f71ef2a7b99c6d148a006891a79d53db82f7f3b/torch_xla/distributed/xla_multiprocessing.py#L163
the string splicing here cannot repeat "grpc://", otherwise Reassigned XRT_WORKERS will have this wrong form grpc://grpc://localhost:40934
These lines of code should look like this
```
    for h, worker in enumerate(wcfg):
      m = re.match(r'(.*):(\d+)$', wcfg[worker].host_port)
      if not m:
        raise RuntimeError('Bad worker HOST:PORT format: {}'.format(
            wcfg[worker].host_port))
      for i in range(0, num_devices):
        gindex = h * num_devices + i
        workers.append('{}:{};{}:{}'.format(wcfg[worker].worker_name, gindex,
                                                   m.group(1),
                                                   int(m.group(2)) + i))
```

**Comment by ZhongYFeng** [comment]
> > > I have not tried it personally, seems like @[cicirori](https://github.com/cicirori) has done it before. Do you mind sharing the config?
> > 
> > 
> > @JackCaoG with pleasure
> > When xmp.spawn starts a GPU task, it ends up using a process to manage a card. xmp.spawn configures some environment variables for each process for distributed launch. The following lists the allowed environment variables and their meanings.
> > env name	meaning	example value
> > XRT_HOST_WORLD_SIZE	number of nodes	INT
> > XRT_HOST_ORDINAL	node index(No need to configure, otherwise it will lead to incorrect running)	INT
> > XRT_SHARD_WORLD_SIZE	number of process (equals to gpu numbers)	INT
> > XRT_SHARD_ORDINAL	global index	INT
> > XRT_SHARD_LOCAL_ORDINAL	local index	INT
> > XRT_MESH_SERVICE_ADDRESS	tf mesh service addr	"${IP}:{PORT}"
> > XRT_WORKERS	global workers info	'|'.join("localservice:${GLOBAL_INDEX};grpc://${IP}:${PORT})
> > XRT_DEVICE_MAP	gloabl device map info	'|'.join("/job:localservice/replica:0/task:${GLOBAL_INDEX}/device:XLA_GPU:0")
> > XRT_LOCAL_WORKER	per worker name	"localservice:${GLOBAL_INDEX}
> > XRT_MULTI_PROCESSING_DEVICE	per worker device	"GPU:${GLOBAL_INDEX}
> > also, CUDA_VISIBLE_DEVICES is needed for per worker. then you need set device ahead in your code:
> > ```
> > device = xm.xla_device()
> > xm.set_replication(device, [device])
> > ```
> 
> Thanks a lot for the answer. But I still encountered some problems, it should be a bug In torch_xla/distributed/xla_multiprocessing.py file ，
> 
> https://github.com/pytorch/xla/blob/9917e41f60354ce96b3181acf30dff422d3c8716/torch_xla/distributed/xla_multiprocessing.py#L54-L63
> 
> 
> https://github.com/pytorch/xla/blob/1f71ef2a7b99c6d148a006891a79d53db82f7f3b/torch_xla/distributed/xla_multiprocessing.py#L147-L175
> 
> 
> In here worker does not have the property host_port, this should be wcfg[worker].host_port
> https://github.com/pytorch/xla/blob/1f71ef2a7b99c6d148a006891a79d53db82f7f3b/torch_xla/distributed/xla_multiprocessing.py#L157
> 
> 
> Same problem with these two lines
> https://github.com/pytorch/xla/blob/1f71ef2a7b99c6d148a006891a79d53db82f7f3b/torch_xla/distributed/xla_multiprocessing.py#L160
> 
> 
> https://github.com/pytorch/xla/blob/1f71ef2a7b99c6d148a006891a79d53db82f7f3b/torch_xla/distributed/xla_multiprocessing.py#L163
> 
> 
> In addition, if XRT_WORKERS="localservice:0;grpc://localhost:40934|localservice:1;grpc://localhost:40937",
> https://github.com/pytorch/xla/blob/1f71ef2a7b99c6d148a006891a79d53db82f7f3b/torch_xla/distributed/xla_multiprocessing.py#L163
> 
> 
> the string splicing here cannot repeat "grpc://", otherwise Reassigned XRT_WORKERS will have this wrong form grpc://grpc://localhost:40934
> These lines of code should look like this
> ```
>     for h, worker in enumerate(wcfg):
>       m = re.match(r'(.*):(\d+)$', wcfg[worker].host_port)
>       if not m:
>         raise RuntimeError('Bad worker HOST:PORT format: {}'.format(
>             wcfg[worker].host_port))
>       for i in range(0, num_devices):
>         gindex = h * num_devices + i
>         workers.append('{}:{};{}:{}'.format(wcfg[worker].worker_name, gindex,
>                                                    m.group(1),
>                                                    int(m.group(2)) + i))
> ```

**Comment by ZhongYFeng** [comment]
> > I have not tried it personally, seems like @[cicirori](https://github.com/cicirori) has done it before. Do you mind sharing the config?
> 
> @JackCaoG with pleasure
> 
> When xmp.spawn starts a GPU task, it ends up using a process to manage a card. xmp.spawn configures some environment variables for each process for distributed launch. The following lists the allowed environment variables and their meanings.
> 
> env name	meaning	example value
> XRT_HOST_WORLD_SIZE	number of nodes	INT
> XRT_HOST_ORDINAL	node index(No need to configure, otherwise it will lead to incorrect running)	INT
> XRT_SHARD_WORLD_SIZE	number of process (equals to gpu numbers)	INT
> XRT_SHARD_ORDINAL	global index	INT
> XRT_SHARD_LOCAL_ORDINAL	local index	INT
> XRT_MESH_SERVICE_ADDRESS	tf mesh service addr	"${IP}:{PORT}"
> XRT_WORKERS	global workers info	'|'.join("localservice:${GLOBAL_INDEX};grpc://${IP}:${PORT})
> XRT_DEVICE_MAP	gloabl device map info	'|'.join("/job:localservice/replica:0/task:${GLOBAL_INDEX}/device:XLA_GPU:0")
> XRT_LOCAL_WORKER	per worker name	"localservice:${GLOBAL_INDEX}
> XRT_MULTI_PROCESSING_DEVICE	per worker device	"GPU:${GLOBAL_INDEX}
> also, CUDA_VISIBLE_DEVICES is needed for per worker. then you need set device ahead in your code:
> 
> ```
> device = xm.xla_device()
> xm.set_replication(device, [device])
> ```

I still have a question. I have two nodes, each node has two gpus. A total of four cards for training
In all_reduce
https://github.com/pytorch/xla/blob/1f71ef2a7b99c6d148a006891a79d53db82f7f3b/torch_xla/core/xla_model.py#L578

**Comment by cicirori** [comment]
don't use any launch utility or functions.
i don't know how much you known about `torch.distributed.launch` (version before pytorch 1.8 has more simple and clear implements).
just follow it, configure the env var above correctly, and do some minor change of you training code, multi-node training will be running as exceptly.

**Comment by ZhongYFeng** [comment]
> don't use any launch utility or functions. i don't know how much you known about `torch.distributed.launch` (version before pytorch 1.8 has more simple and clear implements). just follow it, configure the env var above correctly, and do some minor change of you training code, multi-node training will be running as exceptly.

Does XLA Multi-Node and Multi-GPU need to use torch.distributed.launch to start? Can't start using only torch_xla.distributed.xla_multiprocessing？
I know that in One-Node and Multi-GPU, only need to use torch_xla.distributed.xla_multiprocessing to start it, like this,
https://github.com/pytorch/xla/blob/3ceb226cdf32496f8d6270a50f80528a4e014d78/test/test_train_mp_mnist.py#L177-L189
If possible, can you provide a Multi-Node and Multi-GPU example that can run through as a reference?
thank you very much
